### ISSUE TITLE
minusHours(.5) throws an exception

### ISSUE THREAD

**Issue by nettles-jarrod** [jasonlewis/expressive-date#4]
Trying to use minusHours() with anything less than one but greater than 0 throws the following exception.

```
Exception: DateInterval::__construct(): Unknown or bad format (PT0.5H)
```

There should be a check inside of modifyHours() that looks for floats between 0 and 1 and redirects them to modifyMinutes instead, since its perfectly reasonable that somebody might be trying to pass a fraction of an hour.

**Comment by jasonlewis** [comment]
Sorry for the _extremely_ late reply. I'll get on to this when I can. Thanks for the heads up.

**Comment by jasonlewis** [comment]
After what seems like forever I've finally gotten around to fixing this. Fractions are now allowed.
